import esbuild from 'esbuild';
import process from 'process';
import { builtinModules } from 'node:module';
import { readFile } from 'node:fs/promises';
import { parseHTML } from 'linkedom';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === 'production';

/**
 * Loads a `.svg` file as the inner markup of its root `<svg>` element,
 * matching the format Obsidian's `addIcon` expects (content without the
 * surrounding `<svg>` tag). See:
 * https://docs.obsidian.md/Plugins/User+interface/Icons
 */
const svgIconPlugin = {
	name: 'svg-icon',
	setup(build) {
		build.onLoad({ filter: /\.svg$/ }, async (args) => {
			const source = await readFile(args.path, 'utf8');
			const { document } = parseHTML(source);
			const svg = document.querySelector('svg');
			if (!svg) {
				throw new Error(`No <svg> root element found in ${args.path}`);
			}
			return {
				contents: `export default ${JSON.stringify(svg.innerHTML)};`,
				loader: 'js',
			};
		});
	},
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ['src/main.ts'],
	bundle: true,
	plugins: [svgIconPlugin],
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtinModules,
	],
	format: 'cjs',
	target: 'es2021',
	logLevel: 'info',
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: 'main.js',
	minify: prod,
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}