name: check
on: pull_request
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"
      - name: install
        run: npm install
      - name: test
        run: npm run coverage
      - name: tsc
        run: npm run tsc
      - name: check
        run: npm run ci
env:
  # https://typicode.github.io/husky/guide.html#with-env-variables
  HUSKY: '0'